### ISSUE TITLE
Invalid UTF-8 data 

### ISSUE THREAD

**Issue by MerlionRock** [Furtif/POGOProtos#21]
Got this error when using "GetGymDetailsResponse"

`String field 'pogoprotos.data.PokemonData.deployed_fort_id' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. `

Anyone has any idea what went wrong?

Edit:
Sorry, close it. Use the wrong one

**Comment by Furtif** [comment]
GetGymDetailsResponse No ok good is GymGetInfoResponse
