### ISSUE TITLE
Dump enums in Rpc only and remove the unnecessary prefix in enum names

### ISSUE THREAD

**Issue by Mygod** [Furtif/POGOProtos#32]
Currently `base.proto` contains a lot of enums that are not actually part of `Holoholo.Rpc`, which results in name collisions. For example, `CameraZoomInLevel` is under namespace `Niantic.Holoholo.Combat.Stage` and not part of the Rpc namespace. Currently to get around this, we append a prefix to every enum value, which is less than ideal to say the least.

One possible way to resolve this is to dump a root enum only if it is referenced by some `IMessage`.

I would love to contribute but unfortunately as far as I am concerned the tools for generating the proto are private.

**Comment by Furtif** [comment]
fixed fallow commits last 191 here https://github.com/Furtif/POGOProtos/commit/e544f96a5c1dd8b3107f9d1fc4fb7418a2a3998c
