### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by emlinhax** [Furtif/POGOProtos#43]
Hello Furtif,

I have some questions regarding POGOProtos and POGO itself. Is there any way I could contact you directly?
Discord or Telegram?

Hoping to hear back from you :)

**Comment by Furtif** [comment]
I don't know how much interest it has Public Repo

**Comment by Furtif** [comment]
if you don't know how to use it... it will be complicated I won't be the one to explain all this to you...

have a great continuation
